tgeovox()
{
//=== Macro generated by ROOT version 6.06/00 : Tue Feb 21 14:02:55 2017
//=== Voxel optimization for LCDD Geometry geometry
//===== <run this macro JUST BEFORE closing the geometry>
   TGeoVolume *vol = 0;
   // parse all voxelized volumes
}
